name: CI

on:
  push:
    branches:
      - master
      - renovate/*
    tags:
      - '*'
  pull_request:
  schedule:
    - cron: '0 4 * * 5' # Fridays at 4am

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: wyvox/action@v1
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test:ember

  test-safari:
    name: Test Safari
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: wyvox/action@v1
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test:ember

  test-no-lock:
    name: Floating Dependencies
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout code
        uses: wyvox/action@v1
        with:
          pnpm-args: --no-lockfile
      - name: Test
        run: pnpm test:ember

  test-try:
    name: Scenario ${{ matrix.scenario }}, BS${{ matrix.bootstrap }}, ${{ matrix.browser}}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: ${{ matrix.allow-failure || false }}
    needs:
      - test
    strategy:
      fail-fast: false
      matrix:
        allow-failure:
          - false
        scenario:
          - ember-lts-4.8
          - ember-lts-5.4
          - ember-release
          - ember-beta
          - ember-canary
          - embroider-safe
          - embroider-optimized
        bootstrap:
          - 4
          - 5
        browser:
          - Chrome
        include:
          - scenario: ember-release
            browser: Firefox
            bootstrap: 4
          - scenario: ember-release
            browser: Firefox
            bootstrap: 5
          - scenario: node-tests
          - scenario: tracked-toolbox-v1
            bootstrap: 5
    steps:
      - name: Checkout code
        uses: wyvox/action@v1
      - name: Test
        run: pnpm ember try:one ${{ matrix.scenario }}
        env:
          BOOTSTRAPVERSION: ${{ matrix.bootstrap }}
          BROWSER: ${{ matrix.browser }}

  test-docs:
    name: Docs
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout code
        uses: wyvox/action@v1
      - name: Checkout code
        working-directory: docs
        run: pnpm install
      - name: Run Ember Tests
        run: pnpm test
        working-directory: docs
      - name: Build including API docs
        run: pnpm run docs:build
      # TODO: Perform some basic steps that the build contains API docs
      #       and works as expected.
