name: CI

on:
  push:
    branches:
      - master
      - renovate/*
    tags:
      - '*'
  pull_request:
  schedule:
    - cron: '0 4 * * 5' # Fridays at 4am

jobs:
  test-safari:
    name: Test Safari
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: wyvox/action@v1
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test:ember --config-file testem.safari.js
